### ISSUE TITLE
No Audio - vdr terminates

### ISSUE THREAD

**Issue by hugoboss00** [nafets227/raspi4-vdr-setup#1]
Hi,
After installing using your script (which worked without errors) i connected hdmi0 to the LCD TV and started vdr.
vdr immediately terminates with this error:

> pi@rbvdr:~ $ vdr
AlsaOpenPCM: playback open 'iec958' error: No such device
Aborted

syslog:

> Oct  7 10:32:13 rbvdr vdr: [909] VDR version 2.4.0 started
Oct  7 10:32:13 rbvdr vdr: [909] codeset is 'UTF-8' - known
Oct  7 10:32:13 rbvdr vdr: [909] found 28 locales in /usr/share/locale
Oct  7 10:32:13 rbvdr vdr: [909] loading plugin: /usr/lib/vdr/plugins/libvdr-softhddevice-drm.so.2.4.0
Oct  7 10:32:13 rbvdr vdr: [909] loading plugin: /usr/lib/vdr/plugins/libvdr-cecremote.so.2.4.0
Oct  7 10:32:13 rbvdr vdr: [cecremote] Load keymap
Oct  7 10:32:13 rbvdr vdr: [909] loading /var/lib/vdr/sources.conf
Oct  7 10:32:13 rbvdr vdr: [909] loading /var/lib/vdr/diseqc.conf
Oct  7 10:32:13 rbvdr vdr: [909] loading /var/lib/vdr/scr.conf
Oct  7 10:32:13 rbvdr vdr: [909] loading /var/lib/vdr/channels.conf
Oct  7 10:32:13 rbvdr vdr: [909] loading /var/lib/vdr/commands.conf
Oct  7 10:32:13 rbvdr vdr: [909] loading /var/lib/vdr/reccmds.conf
Oct  7 10:32:13 rbvdr vdr: [909] loading /var/lib/vdr/svdrphosts.conf
Oct  7 10:32:13 rbvdr vdr: [909] loading /var/lib/vdr/keymacros.conf
Oct  7 10:32:13 rbvdr vdr: [909] registered source parameters for 'A - ATSC'
Oct  7 10:32:13 rbvdr vdr: [910] video directory scanner thread started (pid=909, tid=910, prio=low)
Oct  7 10:32:13 rbvdr vdr: [909] registered source parameters for 'C - DVB-C'
Oct  7 10:32:13 rbvdr vdr: [909] registered source parameters for 'S - DVB-S'
Oct  7 10:32:13 rbvdr vdr: [909] registered source parameters for 'T - DVB-T'
Oct  7 10:32:13 rbvdr vdr: [911] epg data reader thread started (pid=909, tid=911, prio=high)
Oct  7 10:32:13 rbvdr vdr: [911] epg data reader thread ended (pid=909, tid=911)
Oct  7 10:32:13 rbvdr vdr: [910] video directory scanner thread ended (pid=909, tid=910)
Oct  7 10:32:13 rbvdr vdr: [909] probing /dev/dvb/adapter0/frontend0
Oct  7 10:32:13 rbvdr vdr: [909] creating cDvbDevice
Oct  7 10:32:13 rbvdr vdr: [909] new device number 1
Oct  7 10:32:13 rbvdr vdr: [909] DVB API version is 0x050B (VDR was built with 0x050B)
Oct  7 10:32:13 rbvdr vdr: [909] frontend 0/0 provides DVB-S,DVB-S2 with QPSK ("Montage Technology M88DS3103")
Oct  7 10:32:13 rbvdr vdr: [913] frontend 0/0 tuner thread started (pid=909, tid=913, prio=high)
Oct  7 10:32:13 rbvdr vdr: [913] cTimeMs: using monotonic clock (resolution is 1 ns)
Oct  7 10:32:13 rbvdr vdr: [909] cTimeMs: using monotonic clock (resolution is 1 ns)
Oct  7 10:32:13 rbvdr vdr: [909] found 1 DVB device
Oct  7 10:32:13 rbvdr vdr: [914] device 1 section handler thread started (pid=909, tid=914, prio=low)
Oct  7 10:32:13 rbvdr vdr: [909] initializing plugin: softhddevice-drm (0.0.1rc1-GITc79a9d3): A software and GPU emulated HD device
Oct  7 10:32:13 rbvdr vdr: [909] new device number 2
Oct  7 10:32:13 rbvdr vdr: [909] initializing plugin: cecremote (1.5.0): Send/Receive CEC commands
Oct  7 10:32:13 rbvdr vdr: [cecremote] Node Name global
Oct  7 10:32:13 rbvdr vdr: [cecremote] Node Name device
Oct  7 10:32:13 rbvdr vdr: [cecremote] Node Name menu
Oct  7 10:32:13 rbvdr vdr: [cecremote] Node Name menu
Oct  7 10:32:13 rbvdr vdr: [cecremote] DEVICE player
Oct  7 10:32:13 rbvdr vdr: [cecremote]    Logical Address = 8
Oct  7 10:32:13 rbvdr vdr: [cecremote]    Global Option cecdebug
Oct  7 10:32:13 rbvdr vdr: [cecremote] CECDebug = 7
Oct  7 10:32:13 rbvdr vdr: [cecremote]    Global Option combokeytimeoutms
Oct  7 10:32:13 rbvdr vdr: [cecremote] ComboKeyTimeoutMs = 1000
Oct  7 10:32:13 rbvdr vdr: [cecremote]    Global Option rtcdetect
Oct  7 10:32:13 rbvdr vdr: [cecremote]    Global Option shutdownonstandby
Oct  7 10:32:13 rbvdr vdr: [cecremote]    Global Option poweroffonstandby
Oct  7 10:32:13 rbvdr vdr: [cecremote]    Global Option onstart
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onstart poweron
Oct  7 10:32:13 rbvdr vdr: [cecremote]          POWERON TV
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onstart makeactive
Oct  7 10:32:13 rbvdr vdr: [cecremote]          MAKEACTIVE
Oct  7 10:32:13 rbvdr vdr: [cecremote]    Global Option onstop
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onstop poweroff
Oct  7 10:32:13 rbvdr vdr: [cecremote]          POWEROFF TV
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onstop poweroff
Oct  7 10:32:13 rbvdr vdr: [cecremote]          POWEROFF player
Oct  7 10:32:13 rbvdr vdr: [cecremote]    Global Option cecdevicetype
Oct  7 10:32:13 rbvdr vdr: [cecremote] CECDevicetype = 1
Oct  7 10:32:13 rbvdr kernel: [  636.833396] hdmi-audio-codec hdmi-audio-codec.1.auto: ASoC: error at snd_soc_dai_startup on i2s-hifi: -19
Oct  7 10:32:13 rbvdr vdr: [cecremote]   Menu Watch DVD (player)
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onstart poweron
Oct  7 10:32:13 rbvdr vdr: [cecremote]          POWERON TV
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onstart poweron
Oct  7 10:32:13 rbvdr vdr: [cecremote]          POWERON player
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onstart makeinactive
Oct  7 10:32:13 rbvdr vdr: [cecremote]          MAKEINACTIVE
Oct  7 10:32:13 rbvdr vdr: [cecremote]          Player StillPic = /video/conf/plugins/cecremote/blueray.mpg
Oct  7 10:32:13 rbvdr vdr: [cecremote]           stop Back
Oct  7 10:32:13 rbvdr vdr: [cecremote]           stop Menu
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onstop poweroff
Oct  7 10:32:13 rbvdr vdr: [cecremote]          POWEROFF player
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onstop makeactive
Oct  7 10:32:13 rbvdr vdr: [cecremote]          MAKEACTIVE
Oct  7 10:32:13 rbvdr vdr: [cecremote]   Menu TV TOGGLE (0)
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onpoweron poweron
Oct  7 10:32:13 rbvdr vdr: [cecremote]          POWERON TV
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onpoweron makeactive
Oct  7 10:32:13 rbvdr vdr: [cecremote]          MAKEACTIVE
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onpoweroff poweroff
Oct  7 10:32:13 rbvdr vdr: [cecremote]          POWEROFF TV
Oct  7 10:32:13 rbvdr vdr: [cecremote]      onpoweroff makeactive
Oct  7 10:32:13 rbvdr vdr: [cecremote]          MAKEACTIVE
Oct  7 10:32:13 rbvdr vdr: [cecremote] Use RTC wakeup detection
Oct  7 10:32:13 rbvdr vdr: [cecremote] Can not open /proc/driver/rtc: No such file or directory
Oct  7 10:32:13 rbvdr vdr: [cecremote] Use VDR wakeup detection: Next Wakeup 0
Oct  7 10:32:13 rbvdr vdr: [cecremote] manual start
Oct  7 10:32:13 rbvdr vdr: [909] setting primary device to 1
Oct  7 10:32:13 rbvdr vdr: [909] device 1 has no MPEG decoder
Oct  7 10:32:13 rbvdr vdr: [909] trying device number 2 instead
Oct  7 10:32:13 rbvdr vdr: [909] setting primary device to 2
Oct  7 10:32:13 rbvdr vdr: [909] [softhddev]MakePrimaryDevice: 1
Oct  7 10:32:13 rbvdr vdr: [915] CEC Thread thread started (pid=909, tid=915, prio=high)
Oct  7 10:32:13 rbvdr vdr: [cecremote] cCECRemote::Connect
Oct  7 10:32:13 rbvdr vdr: [cecremote]    Add device 1
Oct  7 10:32:13 rbvdr vdr: audio/alsa: using device 'iec958'
Oct  7 10:32:13 rbvdr vdr: [cecremote] LibCEC git revision: libcec-6.0.2+1-76551ea, compiled on 2021-09-30 15:34:08 by pi@rbvdr.fritz.box on Linux 5.10.60-v7l+ (armv7l), features: P8_USB, DRM, P8_detect, randr, Linux
Oct  7 10:32:13 rbvdr vdr: audio/alsa: playback open 'iec958' error: No such device

aplay -L shows:

> pi@rbvdr:~ $ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=vc4hdmi0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Default Audio Device
sysdefault:CARD=vc4hdmi0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Default Audio Device
front:CARD=vc4hdmi0,DEV=0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Front speakers
iec958:CARD=vc4hdmi0,DEV=0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=vc4hdmi0,DEV=0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Direct sample mixing device
dsnoop:CARD=vc4hdmi0,DEV=0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Direct sample snooping device
hw:CARD=vc4hdmi0,DEV=0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Direct hardware device without any conversions
plughw:CARD=vc4hdmi0,DEV=0
    vc4-hdmi-0, MAI PCM i2s-hifi-0
    Hardware device with all software conversions
default:CARD=vc4hdmi1
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Default Audio Device
sysdefault:CARD=vc4hdmi1
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Default Audio Device
front:CARD=vc4hdmi1,DEV=0
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Front speakers
iec958:CARD=vc4hdmi1,DEV=0
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=vc4hdmi1,DEV=0
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Direct sample mixing device
dsnoop:CARD=vc4hdmi1,DEV=0
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Direct sample snooping device
hw:CARD=vc4hdmi1,DEV=0
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Direct hardware device without any conversions
plughw:CARD=vc4hdmi1,DEV=0
    vc4-hdmi-1, MAI PCM i2s-hifi-0
    Hardware device with all software conversions

Any idea what could be wrong?
br
Hannes

**Comment by nafets227** [comment]
Did you try on both hdmi ports?

**Comment by hugoboss00** [comment]
hi, yes i did.

after that i tried it with this settings:

> hdmi_force_hotplug=1
hdmi_group=1
hdmi_mode=31
hdmi_mode=1

and i got picture and sound.
I have a (cheap) Medion TV, maybe it depends on the TV if it works out of the box or not...

**Comment by nafets227** [comment]
I´ve seen cases where TV had to be switched on before booting the Raspi. 

Strange is that aplay knows the iec958 device whereas vdr reports to be not able to find it.

I did not catch if the issue is still present or not; if not can this issue be closed?

**Comment by hugoboss00** [comment]
the issue is solved with the above settings in config.txt

> hdmi_force_hotplug=1
hdmi_group=1
hdmi_mode=31
hdmi_mode=1

thanks
